#!/usr/bin/env python3
import json
import argparse
import os
import sys

def generate_inventory(tf_output_path, inventory_path, ssh_key_path):
    try:
        if not os.path.exists(tf_output_path):
             print(f"Error: Terraform output file not found at {tf_output_path}")
             sys.exit(1)

        with open(tf_output_path, 'r') as f:
            data = json.load(f)
        
        # Access the 'value' of the output
        if 'webserver_public_ip' in data:
            ip_address = data['webserver_public_ip']['value']
        else:
            print("Error: 'webserver_public_ip' key not found in JSON data")
            sys.exit(1)
        
        inventory_content = f"""[web]
# Auto-generated by generate_inventory.py
{ip_address} ansible_user=ubuntu ansible_ssh_private_key_file={ssh_key_path}
"""
        
        os.makedirs(os.path.dirname(inventory_path), exist_ok=True)
        with open(inventory_path, 'w') as f:
            f.write(inventory_content)
            
        print(f"Successfully generated inventory at {inventory_path} with IP {ip_address}")
        
    except Exception as e:
        print(f"Error generating inventory: {e}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate Ansible inventory from Terraform outputs')
    parser.add_argument('--tf-output', required=True, help='Path to Terraform output JSON')
    parser.add_argument('--inventory', required=True, help='Path to output inventory file')
    parser.add_argument('--ssh-key', default='~/.ssh/id_ed25519', help='Path to SSH private key')
    
    args = parser.parse_args()
    generate_inventory(args.tf_output, args.inventory, args.ssh_key)
